version: "3.8"

services:
  portfolio_django_app:
    container_name: portofolio_app
    command: gunicorn --bind 0.0.0.0:8000 portfolioproject.wsgi:application && python manage.py makemigrations && python manage.py migrate
    build:
      context: "./"
      dockerfile: ./Dockerfile
    image: "portfolio-app:1.0.0"
    volumes:
      - .:/portfolio-app
    environment:
      - "APP_PORT=8080"
      - "MODE=local"
    ports:
      - "8000:8000"
    networks:
      - network-portfolio
    depends_on:
      - portfolio_postgres_db
      - portfolio_redis
  portfolio_postgres_db:
    image: postgres:alpine3.20
    container_name: portfolio_db
    environment: 
      POSTGRES_PASSWORD: $$DB_PASSWORD
      POSTGRES_USER: $$DB_USER
      POSTGRES_DB: $$DB_NAME
    env_file:
      - .env
    volumes: 
      - type: volume
        source: postgres-portfolio-data
        target: "/var/lib/postgresql/data"
        read_only: false
    ports: 
      - 5432:5432
    networks:
      - network-portfolio
  portfolio_redis:
    image: redis:7.2.5
    container_name: redis_cache
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    env_file:
      .env
    networks:
      - network-portfolio
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - static_data:/static
      - media_data:/media
    ports:
      - 80:80
    depends_on:
      - portfolio_django_app
    networks:
      - network-portfolio

networks:
  network-portfolio:
    name: network-portfolio
    driver: bridge

volumes:
  postgres-portfolio-data:
    name: portfolio-postgresdb-data
  redis_data:
  static_data:
  media_data: