# Generated by Django 3.2.8 on 2021-10-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='year',
            field=models.IntegerField(max_length=4, null=True),
        ),
    ]
