# Generated by Django 3.2.8 on 2021-10-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0002_portfolio_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
