# Generated by Django 3.2.8 on 2021-10-25 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0004_programminglanguage_framework'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-year']},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='url',
            field=models.URLField(null=True, unique=True),
        ),
    ]
