# Generated by Django 3.2.8 on 2021-10-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0005_auto_20211025_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='url',
            field=models.URLField(default='Private', unique=True),
        ),
    ]
