# Generated by Django 3.2.8 on 2021-10-26 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0009_alter_portfolio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='position',
            field=models.CharField(default='Backend Web Developer', max_length=50),
        ),
    ]
